[2024-12-10T09:29:00.440+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-10T09:28:59.561610+00:00 [queued]>
[2024-12-10T09:29:00.452+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-10T09:28:59.561610+00:00 [queued]>
[2024-12-10T09:29:00.453+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-10T09:29:00.470+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-10 09:28:59.561610+00:00
[2024-12-10T09:29:00.473+0000] {standard_task_runner.py:57} INFO - Started process 3374 to run task
[2024-12-10T09:29:00.477+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-10T09:28:59.561610+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmpi3iq9mgg']
[2024-12-10T09:29:00.480+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask run_dbt
[2024-12-10T09:29:00.531+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-10T09:28:59.561610+00:00 [running]> on host 6f9ff553374d
[2024-12-10T09:29:00.618+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T09:28:59.561610+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T09:28:59.561610+00:00'
[2024-12-10T09:29:00.619+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-10T09:29:00.620+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run --rm -v $(pwd)/repo:/app -v $(pwd)/repo/my_dbt_project:/app/my_dbt_project ghcr.io/dbt-labs/dbt-core:1.8.8 run --project-dir /app/my_dbt_project']
[2024-12-10T09:29:00.628+0000] {subprocess.py:86} INFO - Output:
[2024-12-10T09:29:00.654+0000] {subprocess.py:93} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2024-12-10T09:29:00.654+0000] {subprocess.py:93} INFO - See 'docker run --help'.
[2024-12-10T09:29:00.655+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2024-12-10T09:29:00.668+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2024-12-10T09:29:00.673+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241210T092859, start_date=20241210T092900, end_date=20241210T092900
[2024-12-10T09:29:00.687+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task run_dbt (Bash command failed. The command returned a non-zero exit code 125.; 3374)
[2024-12-10T09:29:00.730+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-10T09:29:00.757+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
