[2024-12-10T09:32:25.551+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-10T09:27:22.453580+00:00 [queued]>
[2024-12-10T09:32:25.559+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-10T09:27:22.453580+00:00 [queued]>
[2024-12-10T09:32:25.560+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-10T09:32:25.574+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-10 09:27:22.453580+00:00
[2024-12-10T09:32:25.578+0000] {standard_task_runner.py:57} INFO - Started process 4286 to run task
[2024-12-10T09:32:25.581+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-10T09:27:22.453580+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmpk82gryxh']
[2024-12-10T09:32:25.583+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask run_dbt
[2024-12-10T09:32:25.627+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-10T09:27:22.453580+00:00 [running]> on host 6f9ff553374d
[2024-12-10T09:32:25.708+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-10T09:27:22.453580+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-10T09:27:22.453580+00:00'
[2024-12-10T09:32:25.709+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-10T09:32:25.710+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run --rm -v $(pwd)/repo:/app -v $(pwd)/repo/my_dbt_project:/app/my_dbt_project ghcr.io/dbt-labs/dbt-core:1.8.8 run --project-dir /app/my_dbt_project']
[2024-12-10T09:32:25.717+0000] {subprocess.py:86} INFO - Output:
[2024-12-10T09:32:25.737+0000] {subprocess.py:93} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2024-12-10T09:32:25.738+0000] {subprocess.py:93} INFO - See 'docker run --help'.
[2024-12-10T09:32:25.738+0000] {subprocess.py:97} INFO - Command exited with return code 125
[2024-12-10T09:32:25.748+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2024-12-10T09:32:25.754+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241210T092722, start_date=20241210T093225, end_date=20241210T093225
[2024-12-10T09:32:25.765+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task run_dbt (Bash command failed. The command returned a non-zero exit code 125.; 4286)
[2024-12-10T09:32:25.794+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-10T09:32:25.821+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
