[2024-12-03T16:39:04.884+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_kaggle_data manual__2024-12-03T12:51:10.799908+00:00 [queued]>
[2024-12-03T16:39:04.925+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_kaggle_data manual__2024-12-03T12:51:10.799908+00:00 [queued]>
[2024-12-03T16:39:04.926+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-03T16:39:04.982+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_kaggle_data> on 2024-12-03 12:51:10.799908+00:00
[2024-12-03T16:39:05.000+0000] {standard_task_runner.py:57} INFO - Started process 365 to run task
[2024-12-03T16:39:05.017+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_duckdb', 'download_kaggle_data', 'manual__2024-12-03T12:51:10.799908+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmpan7wxr1a']
[2024-12-03T16:39:05.024+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask download_kaggle_data
[2024-12-03T16:39:05.245+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_duckdb.download_kaggle_data manual__2024-12-03T12:51:10.799908+00:00 [running]> on host 675bf32f24e8
[2024-12-03T16:39:05.583+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_duckdb' AIRFLOW_CTX_TASK_ID='download_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T12:51:10.799908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T12:51:10.799908+00:00'
[2024-12-03T16:39:05.606+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/mannmann2/fortune-500-corporate-headquarters
[2024-12-03T16:39:06.227+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 23, in download_kaggle_dataset
    kaggle.api.dataset_download_file(dataset, file_name, path='/data')
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1460, in dataset_download_file
    _preload_content=False))
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api.py", line 1682, in datasets_download_file_with_http_info
    collection_formats=collection_formats)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api_client.py", line 318, in call_api
    _preload_content, _request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api_client.py", line 149, in __call_api
    _request_timeout=_request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api_client.py", line 339, in request
    headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/rest.py", line 235, in GET
    query_params=query_params)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/rest.py", line 225, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 03 Dec 2024 16:39:07 GMT', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ka_sessionid=e30bec86c14237677429931a9b0e2238; max-age=2626560; path=/, GCLB=CIGovsWR042M8wEQAw; path=/; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Kaggle-MillisecondsElapsed': '272', 'X-Kaggle-RequestId': '27ace0acf3415171a552405e5d8804c9', 'X-Kaggle-ApiVersion': '1.6.17', 'X-Kaggle-HubVersion': '0.3.4', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-YMXH/RGDUPZY2cVphIrguw==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kkb-production.jupyter-proxy.kaggle.net https://kkb-production.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/ ;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'})
HTTP response body: b'{"code":404,"message":"NotFound"}'

[2024-12-03T16:39:06.303+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_to_duckdb, task_id=download_kaggle_data, execution_date=20241203T125110, start_date=20241203T163904, end_date=20241203T163906
[2024-12-03T16:39:06.350+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 80 for task download_kaggle_data ((404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 03 Dec 2024 16:39:07 GMT', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ka_sessionid=e30bec86c14237677429931a9b0e2238; max-age=2626560; path=/, GCLB=CIGovsWR042M8wEQAw; path=/; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Kaggle-MillisecondsElapsed': '272', 'X-Kaggle-RequestId': '27ace0acf3415171a552405e5d8804c9', 'X-Kaggle-ApiVersion': '1.6.17', 'X-Kaggle-HubVersion': '0.3.4', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-YMXH/RGDUPZY2cVphIrguw==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kkb-production.jupyter-proxy.kaggle.net https://kkb-production.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/ ;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'})
HTTP response body: b'{"code":404,"message":"NotFound"}'
; 365)
[2024-12-03T16:39:06.401+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-03T16:39:06.523+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
