[2024-11-11T05:41:18.785+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_kaggle_data scheduled__2024-11-10T05:35:52.727479+00:00 [queued]>
[2024-11-11T05:41:18.797+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_kaggle_data scheduled__2024-11-10T05:35:52.727479+00:00 [queued]>
[2024-11-11T05:41:18.797+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-11-11T05:41:18.826+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_kaggle_data> on 2024-11-10 05:35:52.727479+00:00
[2024-11-11T05:41:18.835+0000] {standard_task_runner.py:57} INFO - Started process 1126 to run task
[2024-11-11T05:41:18.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_duckdb', 'download_kaggle_data', 'scheduled__2024-11-10T05:35:52.727479+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmpgcwbtd0d']
[2024-11-11T05:41:18.841+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask download_kaggle_data
[2024-11-11T05:41:18.910+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_duckdb.download_kaggle_data scheduled__2024-11-10T05:35:52.727479+00:00 [running]> on host 73340d4389ae
[2024-11-11T05:41:19.026+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_duckdb' AIRFLOW_CTX_TASK_ID='download_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T05:35:52.727479+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-10T05:35:52.727479+00:00'
[2024-11-11T05:41:19.033+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/ARMAN/Fortune_500_Corporate_Headquarters.csv
[2024-11-11T05:41:19.285+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 23, in download_kaggle_dataset
    kaggle.api.dataset_download_file(dataset, file_name, path='/data')
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 1460, in dataset_download_file
    _preload_content=False))
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api.py", line 1682, in datasets_download_file_with_http_info
    collection_formats=collection_formats)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api_client.py", line 318, in call_api
    _preload_content, _request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api_client.py", line 149, in __call_api
    _request_timeout=_request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/api_client.py", line 339, in request
    headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/rest.py", line 235, in GET
    query_params=query_params)
  File "/home/airflow/.local/lib/python3.7/site-packages/kaggle/rest.py", line 225, in request
    raise ApiException(http_resp=r)
kaggle.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 11 Nov 2024 05:41:20 GMT', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ka_sessionid=5c8fa82418b9d216ab1f3e0bfc2b3cab; max-age=2626560; path=/, GCLB=COuLsOv7_tTgiAEQAw; path=/; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Kaggle-MillisecondsElapsed': '38', 'X-Kaggle-RequestId': '4eb381f4987946ca170945d598201b36', 'X-Kaggle-ApiVersion': '1.6.17', 'X-Kaggle-HubVersion': '0.3.3', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-EmtCv2XUn8xVLjZX/j8U/A==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kkb-production.jupyter-proxy.kaggle.net https://kkb-production.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/ ;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'})
HTTP response body: b'{"code":403,"message":"Permission \\u0027datasets.get\\u0027 was denied"}'

[2024-11-11T05:41:19.305+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=kaggle_to_duckdb, task_id=download_kaggle_data, execution_date=20241110T053552, start_date=20241111T054118, end_date=20241111T054119
[2024-11-11T05:41:19.335+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 12 for task download_kaggle_data ((403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 11 Nov 2024 05:41:20 GMT', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': 'ka_sessionid=5c8fa82418b9d216ab1f3e0bfc2b3cab; max-age=2626560; path=/, GCLB=COuLsOv7_tTgiAEQAw; path=/; HttpOnly', 'Vary': 'Accept-Encoding', 'X-Kaggle-MillisecondsElapsed': '38', 'X-Kaggle-RequestId': '4eb381f4987946ca170945d598201b36', 'X-Kaggle-ApiVersion': '1.6.17', 'X-Kaggle-HubVersion': '0.3.3', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload', 'Content-Security-Policy': "object-src 'none'; script-src 'nonce-EmtCv2XUn8xVLjZX/j8U/A==' 'report-sample' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/kaggle/20201130; frame-src 'self' https://www.kaggleusercontent.com https://www.youtube.com/embed/ https://polygraph-cool.github.io https://www.google.com/recaptcha/ https://www.docdroid.com https://www.docdroid.net https://kaggle-static.storage.googleapis.com https://kkb-production.jupyter-proxy.kaggle.net https://kkb-production.firebaseapp.com https://kaggle-metastore.firebaseapp.com https://apis.google.com https://content-sheets.googleapis.com/ https://accounts.google.com/ https://storage.googleapis.com https://docs.google.com https://drive.google.com https://calendar.google.com/ ;", 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'})
HTTP response body: b'{"code":403,"message":"Permission \\u0027datasets.get\\u0027 was denied"}'
; 1126)
[2024-11-11T05:41:19.376+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-11-11T05:41:19.407+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
