[2024-12-12T09:20:09.441+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:20:07.764892+00:00 [queued]>
[2024-12-12T09:20:09.454+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:20:07.764892+00:00 [queued]>
[2024-12-12T09:20:09.455+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-12T09:20:09.470+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-12 09:20:07.764892+00:00
[2024-12-12T09:20:09.479+0000] {standard_task_runner.py:57} INFO - Started process 1770 to run task
[2024-12-12T09:20:09.482+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-12T09:20:07.764892+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmpit4e03wj']
[2024-12-12T09:20:09.484+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask run_dbt
[2024-12-12T09:20:09.536+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:20:07.764892+00:00 [running]> on host 15c1365b7b27
[2024-12-12T09:20:09.624+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T09:20:07.764892+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T09:20:07.764892+00:00'
[2024-12-12T09:20:09.626+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T09:20:09.627+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd my_dbt_project && dbt run --models business_transformed']
[2024-12-12T09:20:09.638+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T09:20:09.639+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: my_dbt_project: No such file or directory
[2024-12-12T09:20:09.640+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-12T09:20:09.651+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-12T09:20:09.655+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241212T092007, start_date=20241212T092009, end_date=20241212T092009
[2024-12-12T09:20:09.675+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 169 for task run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 1770)
[2024-12-12T09:20:09.695+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-12T09:20:09.726+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
