[2024-12-03T16:42:04.852+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-03T12:51:10.799908+00:00 [queued]>
[2024-12-03T16:42:04.869+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-03T12:51:10.799908+00:00 [queued]>
[2024-12-03T16:42:04.870+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-03T16:42:04.901+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_and_extract_kaggle_data> on 2024-12-03 12:51:10.799908+00:00
[2024-12-03T16:42:04.912+0000] {standard_task_runner.py:57} INFO - Started process 927 to run task
[2024-12-03T16:42:04.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_duckdb', 'download_and_extract_kaggle_data', 'manual__2024-12-03T12:51:10.799908+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmp47981zwl']
[2024-12-03T16:42:04.920+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask download_and_extract_kaggle_data
[2024-12-03T16:42:04.997+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-03T12:51:10.799908+00:00 [running]> on host 675bf32f24e8
[2024-12-03T16:42:05.147+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_duckdb' AIRFLOW_CTX_TASK_ID='download_and_extract_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T12:51:10.799908+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T12:51:10.799908+00:00'
[2024-12-03T16:42:05.510+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/winston56/fortune-500-data-2021
[2024-12-03T16:42:05.510+0000] {logging_mixin.py:150} INFO - License(s): other
[2024-12-03T16:42:06.092+0000] {logging_mixin.py:150} INFO - Downloading fortune-500-data-2021.zip to /opt/***
[2024-12-03T16:42:06.103+0000] {logging_mixin.py:150} WARNING -   0%|          | 0.00/53.1k [00:00<?, ?B/s]
[2024-12-03T16:42:06.217+0000] {logging_mixin.py:150} WARNING - 100%|##########| 53.1k/53.1k [00:00<00:00, 487kB/s]
[2024-12-03T16:42:06.219+0000] {logging_mixin.py:150} WARNING - 100%|##########| 53.1k/53.1k [00:00<00:00, 475kB/s]
[2024-12-03T16:42:06.226+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 31, in download_and_extract_dataset
    zfile.extractall('/data')
  File "/usr/local/lib/python3.7/zipfile.py", line 1636, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.7/zipfile.py", line 1682, in _extract_member
    os.makedirs(upperdirs)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
[2024-12-03T16:42:06.251+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=kaggle_to_duckdb, task_id=download_and_extract_kaggle_data, execution_date=20241203T125110, start_date=20241203T164204, end_date=20241203T164206
[2024-12-03T16:42:06.283+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 81 for task download_and_extract_kaggle_data ([Errno 13] Permission denied: '/data'; 927)
[2024-12-03T16:42:06.337+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-03T16:42:06.422+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
