[2024-12-03T16:42:24.777+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-03T16:42:21.492255+00:00 [queued]>
[2024-12-03T16:42:24.796+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-03T16:42:21.492255+00:00 [queued]>
[2024-12-03T16:42:24.797+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-03T16:42:24.825+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_and_extract_kaggle_data> on 2024-12-03 16:42:21.492255+00:00
[2024-12-03T16:42:24.835+0000] {standard_task_runner.py:57} INFO - Started process 991 to run task
[2024-12-03T16:42:24.841+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_duckdb', 'download_and_extract_kaggle_data', 'manual__2024-12-03T16:42:21.492255+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmpclk1wixp']
[2024-12-03T16:42:24.844+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask download_and_extract_kaggle_data
[2024-12-03T16:42:24.930+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-03T16:42:21.492255+00:00 [running]> on host 675bf32f24e8
[2024-12-03T16:42:25.074+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_duckdb' AIRFLOW_CTX_TASK_ID='download_and_extract_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T16:42:21.492255+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T16:42:21.492255+00:00'
[2024-12-03T16:42:25.460+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/winston56/fortune-500-data-2021
[2024-12-03T16:42:25.461+0000] {logging_mixin.py:150} INFO - License(s): other
[2024-12-03T16:42:26.079+0000] {logging_mixin.py:150} INFO - fortune-500-data-2021.zip: Skipping, found more recently modified local copy (use --force to force download)
[2024-12-03T16:42:26.084+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 31, in download_and_extract_dataset
    zfile.extractall('/data')
  File "/usr/local/lib/python3.7/zipfile.py", line 1636, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.7/zipfile.py", line 1682, in _extract_member
    os.makedirs(upperdirs)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
[2024-12-03T16:42:26.102+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_to_duckdb, task_id=download_and_extract_kaggle_data, execution_date=20241203T164221, start_date=20241203T164224, end_date=20241203T164226
[2024-12-03T16:42:26.138+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 82 for task download_and_extract_kaggle_data ([Errno 13] Permission denied: '/data'; 991)
[2024-12-03T16:42:26.184+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-03T16:42:26.233+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
