[2024-12-04T09:21:56.272+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_noaa.download_and_extract_kaggle_data scheduled__2024-12-03T09:21:43.756805+00:00 [queued]>
[2024-12-04T09:21:56.288+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_noaa.download_and_extract_kaggle_data scheduled__2024-12-03T09:21:43.756805+00:00 [queued]>
[2024-12-04T09:21:56.289+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-04T09:21:56.314+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_and_extract_kaggle_data> on 2024-12-03 09:21:43.756805+00:00
[2024-12-04T09:21:56.324+0000] {standard_task_runner.py:57} INFO - Started process 937 to run task
[2024-12-04T09:21:56.329+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_noaa', 'download_and_extract_kaggle_data', 'scheduled__2024-12-03T09:21:43.756805+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmpdw8np8fo']
[2024-12-04T09:21:56.332+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask download_and_extract_kaggle_data
[2024-12-04T09:21:56.408+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_noaa.download_and_extract_kaggle_data scheduled__2024-12-03T09:21:43.756805+00:00 [running]> on host 331557b4d310
[2024-12-04T09:21:56.521+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_noaa' AIRFLOW_CTX_TASK_ID='download_and_extract_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T09:21:43.756805+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-03T09:21:43.756805+00:00'
[2024-12-04T09:21:56.966+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/mannmann2/fortune-500-corporate-headquarters
[2024-12-04T09:21:56.967+0000] {logging_mixin.py:150} INFO - License(s): CC0-1.0
[2024-12-04T09:21:57.478+0000] {logging_mixin.py:150} INFO - Downloading fortune-500-corporate-headquarters.zip to /opt/***
[2024-12-04T09:21:57.482+0000] {logging_mixin.py:150} WARNING -   0%|          | 0.00/37.6k [00:00<?, ?B/s]
[2024-12-04T09:21:57.580+0000] {logging_mixin.py:150} WARNING - 100%|##########| 37.6k/37.6k [00:00<00:00, 397kB/s]
[2024-12-04T09:21:57.586+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 29, in download_and_extract_dataset
    zfile.extractall('./data')
  File "/usr/local/lib/python3.7/zipfile.py", line 1636, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.7/zipfile.py", line 1690, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'data/Fortune_500_Corporate_Headquarters.csv'
[2024-12-04T09:21:57.600+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_to_noaa, task_id=download_and_extract_kaggle_data, execution_date=20241203T092143, start_date=20241204T092156, end_date=20241204T092157
[2024-12-04T09:21:57.633+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 112 for task download_and_extract_kaggle_data ([Errno 13] Permission denied: 'data/Fortune_500_Corporate_Headquarters.csv'; 937)
[2024-12-04T09:21:57.668+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-04T09:21:57.698+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
