[2024-12-12T09:23:07.859+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:18:04.476613+00:00 [queued]>
[2024-12-12T09:23:07.868+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:18:04.476613+00:00 [queued]>
[2024-12-12T09:23:07.869+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-12T09:23:07.882+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-12 09:18:04.476613+00:00
[2024-12-12T09:23:07.887+0000] {standard_task_runner.py:57} INFO - Started process 3119 to run task
[2024-12-12T09:23:07.890+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-12T09:18:04.476613+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmpj6pau8gv']
[2024-12-12T09:23:07.893+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask run_dbt
[2024-12-12T09:23:07.939+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:18:04.476613+00:00 [running]> on host 15c1365b7b27
[2024-12-12T09:23:08.006+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T09:18:04.476613+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T09:18:04.476613+00:00'
[2024-12-12T09:23:08.008+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T09:23:08.009+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd my_dbt_project && dbt run --models business_transformed']
[2024-12-12T09:23:08.018+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T09:23:08.020+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: my_dbt_project: No such file or directory
[2024-12-12T09:23:08.020+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-12T09:23:08.030+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-12T09:23:08.034+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241212T091804, start_date=20241212T092307, end_date=20241212T092308
[2024-12-12T09:23:08.045+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 171 for task run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 3119)
[2024-12-12T09:23:08.063+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-12T09:23:08.128+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
